# Generated by Django 2.2.14 on 2020-10-28 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='related_to',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='gestao.Categoria'),
        ),
    ]
