# Generated by Django 2.2.14 on 2020-10-28 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestao', '0002_auto_20201028_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoria',
            name='related_to',
        ),
        migrations.AddField(
            model_name='categoria',
            name='categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categorias', to='gestao.Categoria'),
        ),
    ]
